apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetik-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetik-app
  template:
    metadata:
      labels:
        app: kubernetik-app
    spec:
      containers:
        - name: kubernetik-app
          image: doublegrey/kubernetik_app:latest
          env:
            - name: BROKER
              value: "172.17.133.2:9092"
            - name: TOPIC
              value: "k8s"
          ports:
            - containerPort: 9092
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
